USE [GuiaMinera]
GO
INSERT INTO Pais (id, codigo, nombre_pais)
SELECT ROW_NUMBER() OVER (
        ORDER BY (
                SELECT NULL
            )
    ),
    codigo,
    nombre_pais
FROM (
        VALUES ('AFG', 'Afganist�n'),
            ('ALB', 'Albania'),
            ('DEU', 'Alemania'),
            ('AND', 'Andorra'),
            ('AGO', 'Angola'),
            ('AIA', 'Anguila'),
            ('ATA', 'Ant�rtida'),
            ('ATG', 'Antigua y Barbuda'),
            ('SAU', 'Arabia Saudita'),
            ('DZA', 'Argelia'),
            ('ARG', 'Argentina'),
            ('ARM', 'Armenia'),
            ('ABW', 'Aruba'),
            ('AUS', 'Australia'),
            ('AUT', 'Austria'),
            ('AZE', 'Azerbaiy�n'),
            ('BHS', 'Bahamas'),
            ('BGD', 'Banglad�s'),
            ('BRB', 'Barbados'),
            ('BHR', 'Bar�in'),
            ('BEL', 'B�lgica'),
            ('BLZ', 'Belice'),
            ('BEN', 'Ben�n'),
            ('BMU', 'Bermudas'),
            ('BLR', 'Bielorrusia'),
            ('MMR', 'Myanmar'),
            ('BOL', 'Bolivia'),
            ('BIH', 'Bosnia y Herzegovina'),
            ('BWA', 'Botsuana'),
            ('BRA', 'Brasil'),
            ('BRN', 'Brun�i Darussalam'),
            ('BGR', 'Bulgaria'),
            ('BFA', 'Burkina Faso'),
            ('BDI', 'Burundi'),
            ('BTN', 'But�n'),
            ('CPV', 'Cabo Verde'),
            ('KHM', 'Camboya'),
            ('CMR', 'Camer�n'),
            ('CAN', 'Canad�'),
            ('QAT', 'Catar'),
            ('BES', 'Bonaire'),
            ('TCD', 'Chad'),
            ('CHL', 'Chile'),
            ('CHN', 'China'),
            ('CYP', 'Chipre'),
            ('COL', 'Colombia'),
            ('COM', 'Comoras'),
            ('KOR', 'Corea'),
            ('CIV', 'Costa de Marfil'),
            ('CRI', 'Costa Rica'),
            ('HRV', 'Croacia'),
            ('CUB', 'Cuba'),
            ('CUW', 'Cura�ao'),
            ('DNK', 'Dinamarca'),
            ('DMA', 'Dominica'),
            ('ECU', 'Ecuador'),
            ('EGY', 'Egipto'),
            ('SLV', 'El Salvador'),
            ('ARE', 'Emiratos �rabes Unidos'),
            ('ERI', 'Eritrea'),
            ('SVK', 'Eslovaquia'),
            ('SVN', 'Eslovenia'),
            ('ESP', 'Espa�a'),
            ('USA', 'Estados Unidos'),
            ('EST', 'Estonia'),
            ('ETH', 'Etiop�a'),
            ('PHL', 'Filipinas'),
            ('FIN', 'Finlandia'),
            ('FJI', 'Fiyi'),
            ('FRA', 'Francia'),
            ('GAB', 'Gab�n'),
            ('GMB', 'Gambia'),
            ('GEO', 'Georgia'),
            ('GHA', 'Ghana'),
            ('GIB', 'Gibraltar'),
            ('GRD', 'Granada'),
            ('GRC', 'Grecia'),
            ('GRL', 'Groenlandia'),
            ('GLP', 'Guadalupe'),
            ('GUM', 'Guam'),
            ('GTM', 'Guatemala'),
            ('GUF', 'Guayana Francesa'),
            ('GGY', 'Guernsey'),
            ('GIN', 'Guinea'),
            ('GNB', 'Guinea-Bis�u'),
            ('GNQ', 'Guinea Ecuatorial'),
            ('GUY', 'Guyana'),
            ('HTI', 'Hait�'),
            ('HND', 'Honduras'),
            ('HKG', 'Hong Kong'),
            ('HUN', 'Hungr�a'),
            ('IND', 'India'),
            ('IDN', 'Indonesia'),
            ('IRQ', 'Irak'),
            ('IRN', 'Ir�n'),
            ('IRL', 'Irlanda'),
            ('BVT', 'Isla Bouvet'),
            ('IMN', 'Isla de Man'),
            ('CXR', 'Isla de Navidad'),
            ('NFK', 'Isla Norfolk'),
            ('ISL', 'Islandia'),
            ('CYM', 'Islas Caim�n'),
            ('CCK', 'Islas Cocos'),
            ('COK', 'Islas Cook'),
            ('FRO', 'Islas Feroe'),
            (
                'SGS',
                'Georgia del sur y las islas sandwich del sur'
            ),
            ('HMD', 'Isla Heard e Islas McDonald'),
            ('FLK', 'Islas Malvinas'),
            ('MNP', 'Islas Marianas del Norte'),
            ('MHL', 'Islas Marshall'),
            ('PCN', 'Pitcairn'),
            ('SLB', 'Islas Salom�n'),
            ('TCA', 'Islas Turcas y Caicos'),
            (
                'UMI',
                'Islas de Ultramar Menores de Estados Unidos'
            ),
            ('VIR', 'Islas V�rgenes'),
            ('ISR', 'Israel'),
            ('ITA', 'Italia'),
            ('JAM', 'Jamaica'),
            ('JPN', 'Jap�n'),
            ('JEY', 'Jersey'),
            ('JOR', 'Jordania'),
            ('KAZ', 'Kazajist�n'),
            ('KEN', 'Kenia'),
            ('KGZ', 'Kirguist�n'),
            ('KIR', 'Kiribati'),
            ('KWT', 'Kuwait'),
            ('LAO', 'Lao'),
            ('LSO', 'Lesoto'),
            ('LVA', 'Letonia'),
            ('LBN', 'L�bano'),
            ('LBR', 'Liberia'),
            ('LBY', 'Libia'),
            ('LIE', 'Liechtenstein'),
            ('LTU', 'Lituania'),
            ('LUX', 'Luxemburgo'),
            ('MAC', 'Macao'),
            ('MDG', 'Madagascar'),
            ('MYS', 'Malasia'),
            ('MWI', 'Malaui'),
            ('MDV', 'Maldivas'),
            ('MLI', 'Mal�'),
            ('MLT', 'Malta'),
            ('MAR', 'Marruecos'),
            ('MTQ', 'Martinica'),
            ('MUS', 'Mauricio'),
            ('MRT', 'Mauritania'),
            ('MYT', 'Mayotte'),
            ('MEX', 'M�xico'),
            ('FSM', 'Micronesia'),
            ('MDA', 'Moldavia'),
            ('MCO', 'M�naco'),
            ('MNG', 'Mongolia'),
            ('MNE', 'Montenegro'),
            ('MSR', 'Montserrat'),
            ('MOZ', 'Mozambique'),
            ('NAM', 'Namibia'),
            ('NRU', 'Nauru'),
            ('NPL', 'Nepal'),
            ('NIC', 'Nicaragua'),
            ('NER', 'N�ger'),
            ('NGA', 'Nigeria'),
            ('NIU', 'Niue'),
            ('NOR', 'Noruega'),
            ('NCL', 'Nueva Caledonia'),
            ('NZL', 'Nueva Zelanda'),
            ('OMN', 'Om�n'),
            ('NLD', 'Pa�ses Bajos'),
            ('PAK', 'Pakist�n'),
            ('PLW', 'Palaos'),
            ('PSE', 'Palestina, Estado de'),
            ('PAN', 'Panam�'),
            ('PNG', 'Pap�a Nueva Guinea'),
            ('PRY', 'Paraguay'),
            ('PER', 'Per�'),
            ('PYF', 'Polinesia Francesa'),
            ('POL', 'Polonia'),
            ('PRT', 'Portugal'),
            ('PRI', 'Puerto Rico'),
            ('GBR', 'Reino Unido'),
            ('CAF', 'Rep�blica Centroafricana'),
            ('CZE', 'Rep�blica Checa'),
            ('MKD', 'Macedonia'),
            ('COG', 'Congo'),
            ('DOM', 'Rep�blica Dominicana'),
            ('REU', 'Reuni�n'),
            ('RWA', 'Ruanda'),
            ('ROU', 'Rumania'),
            ('RUS', 'Rusia'),
            ('ESH', 'Sahara Occidental'),
            ('WSM', 'Samoa'),
            ('ASM', 'Samoa Americana'),
            ('BLM', 'San Bartolom�'),
            ('KNA', 'San Crist�bal y Nieves'),
            ('SMR', 'San Marino'),
            ('MAF', 'San Mart�n'),
            ('SPM', 'San Pedro y Miquel�n'),
            ('VCT', 'San Vicente y las Granadinas'),
            ('SHN', 'Santa Helena'),
            ('LCA', 'Santa Luc�a'),
            ('STP', 'Santo Tom� y Pr�ncipe'),
            ('SEN', 'Senegal'),
            ('SRB', 'Serbia'),
            ('SYC', 'Seychelles'),
            ('SLE', 'Sierra leona'),
            ('SGP', 'Singapur'),
            ('SXM', 'Sint Maarten'),
            ('SYR', 'Siria'),
            ('SOM', 'Somalia'),
            ('LKA', 'Sri Lanka'),
            ('SWZ', 'Suazilandia'),
            ('ZAF', 'Sud�frica'),
            ('SDN', 'Sud�n'),
            ('SSD', 'Sud�n del Sur'),
            ('SWE', 'Suecia'),
            ('CHE', 'Suiza'),
            ('SUR', 'Surinam'),
            ('SJM', 'Svalbard y Jan Mayen'),
            ('THA', 'Tailandia'),
            ('TWN', 'Taiw�n'),
            ('TZA', 'Tanzania'),
            ('TJK', 'Tayikist�n'),
            ('IOT', 'Territorio Brit�nico del Oc�ano �ndico'),
            ('ATF', 'Territorios Australes Franceses'),
            ('TLS', 'Timor-Leste'),
            ('TGO', 'Togo'),
            ('TKL', 'Tokelau'),
            ('TON', 'Tonga'),
            ('TTO', 'Trinidad y Tobago'),
            ('TUN', 'T�nez'),
            ('TKM', 'Turkmenist�n'),
            ('TUR', 'Turqu�a'),
            ('TUV', 'Tuvalu'),
            ('UKR', 'Ucrania'),
            ('UGA', 'Uganda'),
            ('URY', 'Uruguay'),
            ('UZB', 'Uzbekist�n'),
            ('VUT', 'Vanuatu'),
            ('VEN', 'Venezuela'),
            ('VNM', 'Vietnam'),
            ('WLF', 'Wallis y Futuna'),
            ('YEM', 'Yemen'),
            ('DJI', 'Yibuti'),
            ('ZMB', 'Zambia'),
            ('ZWE', 'Zimbabue')
    ) AS Data(codigo, nombre_pais);
GO